### ISSUE TITLE
Add goodonyou.eco

### ISSUE THREAD

**Issue by lemnis** [sdassow/awesome-veganism#11]
goodonyou.eco is a great resource to find vegan brands. (Personally I use it as a starting point for finding sustainable brands). I can't confirm if brands that are labelled "vegan" are always 100% vegan, but it is a great resource to discover vegan clothing brands.

To filter to only vegan brans follow these steps:
1.  Go to a specific category, e.g. https://directory.goodonyou.eco/categories/shoes
2. Click on refine
<img width="685" alt="image" src="https://user-images.githubusercontent.com/3999815/125066943-e3c46980-e0b3-11eb-872d-eb27b308c053.png">
3. Scroll down and collapse Values
<img width="429" alt="image" src="https://user-images.githubusercontent.com/3999815/125067091-12424480-e0b4-11eb-9b40-245b23748ceb.png">
4. Click on "vegan" 
5. Press "done"
6. Now it shows only brands marked as vegan by goodonyou 🙂

**Comment by sdassow** [comment]
The sentiment is appreciated, but since only 47 out of 724 brands on the page are vegan (7%), I doubt it's worth adding as a resource itself. Maybe some of the products are so awesome that they deserve individual recommendations though?

**Comment by sdassow** [comment]
Going to close this as there hasn't been any follow-up.
Specifically curated additions from anyone are of course still welcome.
