### ISSUE TITLE
Generate RSS feed

### ISSUE THREAD

**Issue by sdassow** [sdassow/awesome-veganism#19]
Find a way to generate an RSS feed to publish additions / removals from the list.

**Comment by Marzal** [comment]
Hi, right now the easiest solution would be to advertise:

https://github.com/sdassow/awesome-veganism/commits.atom
That's the RSS/ATOM feed for all commits.

Also you can have the feed for only a `branch`:
https://github.com/sdassow/awesome-veganism/commits/main.atom

There is also this RSS for `tags`
https://github.com/sdassow/awesome-veganism/tags.atom

and for `Releases`
https://github.com/sdassow/awesome-veganism/releases.atom

Is not super user friendly but is something.

**Comment by sdassow** [comment]
That's indeed easy, but also lacking in terms of being user friendly as you're pointing out.
I've was searching if some tool does this already, but due to the specific nature of the content started looking into parsing the git log and how to create a nicer version that is more in line with having curated entries. Probably going to push some code soon. Should all of that fail the commits feed still is an option of course. Thanks for pointing that out.

**Comment by sdassow** [comment]
Just pushed the code: https://github.com/sdassow/awesome-veganism-feed
Still have to integrate it with the website though.

**Comment by sdassow** [comment]
News feeds are up (RSS, ATOM, and JSON).
One more thing is to add a nice icon so the existence is more obvious.

**Comment by sdassow** [comment]
Icon with link to atom feed added as well :-)
